name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Format, Run Analysis and Test
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "code is not formatted, please run 'go fmt ./...'" && exit 1
          fi
          export PATH="$PATH:$(go env GOPATH)/bin"
          go get honnef.co/go/tools/...
          staticcheck $(go list ./...)
          go test ./...